### Write a Python program to count the occurrences of each element in a list.

In [81]:
# Creation of function

def count_occurrences(lista):
    count={}
    for item in lista:
        count[item]=lista.count(item)
    return count


In [82]:
#Call Function 
list1=[11,22,33,44,55,44,33,44,33,22,22,22,11,11,11]

count_occurrences(list1)

{11: 4, 22: 4, 33: 3, 44: 3, 55: 1}

### WAF to Check for Palindrome

In [3]:
# Declartion of function

def palindrome(a):
    if (a==a[: :-1]):
        print("Yes, it is a Palindrome")
    else:
        print("No, it is not a Palindrome")

In [4]:
# Call Function 

stri="radar"

palindrome(stri)

Yes, it is a Palindrome


### WAF to Remove Duplicates from a List

In [5]:
# Declartion of function

def dupli_remove(a):
    return set(a)

In [6]:
# Call Function

list1=[11,22,44,33,44,55,44,33,44,33,22,22,22,11,11,11]

dupli_remove(list1)


{11, 22, 33, 44, 55}

### Write a function to find the maximum number in a list.

In [7]:
# Declartion of function
def maximum(a):
    return max(a)

In [8]:
# Call Function

list1=[11,22,33,44,55,44,33,44,33,22,22,22,11,11,11]

maximum(list1)

55

### Write a function to reverse a string.

In [9]:
# Declartion of function
def reverse(a):
    print(a[ : :-1])

In [10]:
# Call Function

stri='Hello'

reverse(stri)

olleH


### Write a Python program to print all prime numbers between 1 and 100.

In [11]:
# Declartion of function

def prime_till(n):
    li=[]
    for i in range(2,n+1):
        count=0
        for a in range(1,i+1):
            if(i%a==0):
                count=count+1
        if(count==2):
            li.append(i)
    return li

In [12]:
# calling Function
prime_till(50)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

### Given a list of numbers, write a function to return the second largest number

In [74]:
# Declartion of the function
def second_largest(l):
    l.sort()
    return l[-2]

In [75]:
# Calling function
list1=[11,22,33,44,55,44,33,44,33,22,22,22,11,11,11]
second_largest(list1)

44

### How would you reverse a string.

In [15]:
# Declartion of the function
def reverse(a):
    reve=a[: :-1]
    return reve

In [16]:
# Calling function
stri="Hello"
reverse(stri)

'olleH'

Write a Python program to read a file and count the number of lines and words in it.

### Create a function to calculate the factorial of a number using recursion.

In [17]:
# Declartion of function 

def factorial(n):
    if n==1 or n==0:
        return 1
    else:
        return n*factorial(n-1)

In [18]:
# Calling function
factorial(5)

120

### Write a Python program to create a 3x3 NumPy array of all ones and replace the diagonal elements with zeros.

In [19]:
import numpy as np

In [20]:
ones=np.ones((3,3),dtype=int)
print(ones)
print("")
for i in range(len(ones)):
    ones[i,i]=0
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 1 1]
 [1 0 1]
 [1 1 0]]


### Create a NumPy array of random numbers between 0 and 1 and filter out all values greater than 0.5.

In [21]:
a=np.random.random((5,5))
a

array([[0.77676467, 0.56082299, 0.52235655, 0.77006279, 0.03220439],
       [0.30197438, 0.6935087 , 0.78723494, 0.57750682, 0.38017526],
       [0.72952152, 0.47363586, 0.73028905, 0.16064053, 0.86365196],
       [0.25793456, 0.55369831, 0.15185362, 0.13640224, 0.61930228],
       [0.87066682, 0.15316145, 0.87692134, 0.5183703 , 0.50809509]])

In [22]:
print(a[a>0.5])

[0.77676467 0.56082299 0.52235655 0.77006279 0.6935087  0.78723494
 0.57750682 0.72952152 0.73028905 0.86365196 0.55369831 0.61930228
 0.87066682 0.87692134 0.5183703  0.50809509]


### Given a NumPy array [1, 2, 3, 4, 5], calculate the mean and standard deviation.

In [23]:
z=np.array([1, 2, 3, 4, 5])
z

array([1, 2, 3, 4, 5])

In [24]:
print(np.mean(z))
print(np.std(z))

3.0
1.4142135623730951


### Write a Python program to perform element-wise addition, subtraction, multiplication, and division on two given arrays.

In [25]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([6, 7, 8, 9, 10])

In [26]:
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


### Write a Python program to extract all even numbers from a NumPy array.

In [27]:
b=np.array([6, 7, 8, 9, 10])

In [28]:
print(b[b%2==0])

[ 6  8 10]


### How would you reshape a 1D NumPy array of size 9 into a 3x3 matrix?

In [29]:
b=np.array([6, 7, 8, 9, 10,11,12,13,14])
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
b=b.reshape((3,3))
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Write a Python program to find the minimum and maximum values in a 2D NumPy array along a specific axis.

In [31]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [32]:
print(b.max(axis=0))
print(b.min(axis=0))

[12 13 14]
[6 7 8]


### How would you calculate the cumulative sum of a NumPy array?

In [33]:
c=np.array([6, 7, 8, 9, 10,11,12,13,14])
c

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
c.sum()

90

### Create a pandas DataFrame from a dictionary and add a new column based on existing data.

In [35]:
# creation of dictionary
dic={"Name":["Simran","Prateek","Suman","Nonu"],
     "Age":[26,31,22,29],
     "Location":["Ggn","Ggn","Delhi","Chamoli"],
    "Profession":["Data Analyst","Business-man","Cook","Vet Doctor"]}
dic

{'Name': ['Simran', 'Prateek', 'Suman', 'Nonu'],
 'Age': [26, 31, 22, 29],
 'Location': ['Ggn', 'Ggn', 'Delhi', 'Chamoli'],
 'Profession': ['Data Analyst', 'Business-man', 'Cook', 'Vet Doctor']}

In [36]:
import pandas as pd

C:\Users\Admin\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [37]:
# Convert into DataFrame
data=pd.DataFrame(dic)
data

Name  Age Location    Profession
0   Simran   26      Ggn  Data Analyst
1  Prateek   31      Ggn  Business-man
2    Suman   22    Delhi          Cook
3     Nonu   29  Chamoli    Vet Doctor

In [38]:
#Add new column
data["Fav_colour"]=["Yellow","Blue","Red","Green"]
data

Name  Age Location    Profession Fav_colour
0   Simran   26      Ggn  Data Analyst     Yellow
1  Prateek   31      Ggn  Business-man       Blue
2    Suman   22    Delhi          Cook        Red
3     Nonu   29  Chamoli    Vet Doctor      Green

In [39]:
#Add new row
data.loc[4]=["Zina",24,"Dubai","Singer","Orange"]
data

Name  Age Location    Profession Fav_colour
0   Simran   26      Ggn  Data Analyst     Yellow
1  Prateek   31      Ggn  Business-man       Blue
2    Suman   22    Delhi          Cook        Red
3     Nonu   29  Chamoli    Vet Doctor      Green
4     Zina   24    Dubai        Singer     Orange

In [40]:
#Edit DataFrame changing age of Zina to 27

data.loc[data["Name"]=="Zina","Age"]=27
data

Name  Age Location    Profession Fav_colour
0   Simran   26      Ggn  Data Analyst     Yellow
1  Prateek   31      Ggn  Business-man       Blue
2    Suman   22    Delhi          Cook        Red
3     Nonu   29  Chamoli    Vet Doctor      Green
4     Zina   27    Dubai        Singer     Orange

### Write a Python program to sort a DataFrame by multiple columns.

In [41]:
data.sort_values(["Location","Age"],ascending=[True,True])
data

Name  Age Location    Profession Fav_colour
0   Simran   26      Ggn  Data Analyst     Yellow
1  Prateek   31      Ggn  Business-man       Blue
2    Suman   22    Delhi          Cook        Red
3     Nonu   29  Chamoli    Vet Doctor      Green
4     Zina   27    Dubai        Singer     Orange

### Write a Python program to drop rows with missing values in a pandas DataFrame.

In [42]:
data.loc[5]=["Ankit",np.nan, "Bihar","SDE","Black"]
data

Name   Age Location    Profession Fav_colour
0   Simran  26.0      Ggn  Data Analyst     Yellow
1  Prateek  31.0      Ggn  Business-man       Blue
2    Suman  22.0    Delhi          Cook        Red
3     Nonu  29.0  Chamoli    Vet Doctor      Green
4     Zina  27.0    Dubai        Singer     Orange
5    Ankit   NaN    Bihar           SDE      Black

In [43]:
data=data.dropna()
data

Name   Age Location    Profession Fav_colour
0   Simran  26.0      Ggn  Data Analyst     Yellow
1  Prateek  31.0      Ggn  Business-man       Blue
2    Suman  22.0    Delhi          Cook        Red
3     Nonu  29.0  Chamoli    Vet Doctor      Green
4     Zina  27.0    Dubai        Singer     Orange

### Given a DataFrame, replace all occurrences of a specific value with another value.

In [44]:
data=data.replace(to_replace="Ggn",value="Gurgoan")
data

Name   Age Location    Profession Fav_colour
0   Simran  26.0  Gurgoan  Data Analyst     Yellow
1  Prateek  31.0  Gurgoan  Business-man       Blue
2    Suman  22.0    Delhi          Cook        Red
3     Nonu  29.0  Chamoli    Vet Doctor      Green
4     Zina  27.0    Dubai        Singer     Orange

### Write a Python program to select rows of a DataFrame where a column value is greater than a given threshold.

In [45]:
filtered=data[data["Age"]>26]
filtered

Name   Age Location    Profession Fav_colour
1  Prateek  31.0  Gurgoan  Business-man       Blue
3     Nonu  29.0  Chamoli    Vet Doctor      Green
4     Zina  27.0    Dubai        Singer     Orange

### Extract specific columns from a DataFrame and save them to a CSV file.

In [46]:
data1=data["Name"]
data1

0     Simran
1    Prateek
2      Suman
3       Nonu
4       Zina
Name: Name, dtype: object

In [48]:
data1.to_csv("Data")

### Write a Python program to group a DataFrame by a column and calculate the mean of another column.

In [51]:
new=data.groupby("Location")["Age"].mean()
new

Location
Chamoli    29.0
Delhi      22.0
Dubai      27.0
Gurgoan    28.5
Name: Age, dtype: float64

### How would you find the total, mean, and count of a column grouped by another column?

In [52]:
new=data.groupby("Location")["Age"].agg(["sum","mean","count"])
new

sum  mean  count
Location                   
Chamoli   29.0  29.0      1
Delhi     22.0  22.0      1
Dubai     27.0  27.0      1
Gurgoan   57.0  28.5      2

### Write a Python program to merge two DataFrames on a common column.

In [54]:
# Create raw data for the first DataFrame
data1 = {
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
}

data2 = {
    'ID': [3, 4, 5, 6],
    'Department': ['HR', 'Finance', 'IT', 'Marketing'],
    'Salary': [50000, 60000, 70000, 80000]
}

# Create DataFrames from raw data
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print(df1)

print(df2)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
   ID Department  Salary
0   3         HR   50000
1   4    Finance   60000
2   5         IT   70000
3   6  Marketing   80000


In [56]:
newdf=pd.merge(df1,df2,how="left", on="ID")
newdf

ID     Name  Age Department   Salary
0   1    Alice   25        NaN      NaN
1   2      Bob   30        NaN      NaN
2   3  Charlie   35         HR  50000.0
3   4    David   40    Finance  60000.0

### How would you concatenate two DataFrames vertically and reset the index?

In [58]:
# First DataFrame
data1 = {
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
}
df1 = pd.DataFrame(data1)

# Second DataFrame
data2 = {
    'ID': [4, 5, 6],
    'Name': ['David', 'Eve', 'Frank'],
    'Score': [88, 92, 96]
}
df2 = pd.DataFrame(data2)

print(df1)
print(df2)

   ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     95
   ID   Name  Score
0   4  David     88
1   5    Eve     92
2   6  Frank     96


In [62]:
newdata1=pd.concat((df1,df2),ignore_index=True)
newdata1

ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     95
3   4    David     88
4   5      Eve     92
5   6    Frank     96

### Write a Python program to convert a column of strings to datetime objects.

In [67]:
data = {
    'Date_String': ['2025-01-01', '2025-01-15', '2025-01-22', '2025-02-01']
}
df = pd.DataFrame(data)
df

Date_String
0  2025-01-01
1  2025-01-15
2  2025-01-22
3  2025-02-01

In [68]:
df["Date"]=pd.to_datetime(df["Date_String"])
df

Date_String       Date
0  2025-01-01 2025-01-01
1  2025-01-15 2025-01-15
2  2025-01-22 2025-01-22
3  2025-02-01 2025-02-01

### How would you resample a time-series DataFrame to calculate weekly averages?

In [69]:
data = {
    'Date': pd.date_range(start='2025-01-01', periods=14, freq='D'),  # Daily frequency
    'Value': [10, 12, 14, 13, 15, 18, 20, 22, 25, 23, 21, 19, 17, 16]
}
df = pd.DataFrame(data)
df

Date  Value
0  2025-01-01     10
1  2025-01-02     12
2  2025-01-03     14
3  2025-01-04     13
4  2025-01-05     15
5  2025-01-06     18
6  2025-01-07     20
7  2025-01-08     22
8  2025-01-09     25
9  2025-01-10     23
10 2025-01-11     21
11 2025-01-12     19
12 2025-01-13     17
13 2025-01-14     16

In [73]:
weekly=df.resample('W',on="Date")["Value"].mean()
weekly

Date
2025-01-05    12.800000
2025-01-12    21.142857
2025-01-19    16.500000
Freq: W-SUN, Name: Value, dtype: float64

Write a Python program that:

Reads a CSV file containing sales data (e.g., date, product, sales).
Calculates the total sales for each product using pandas.
Creates a new column showing the percentage of total sales contributed by each product.
Saves the updated DataFrame to a new CSV file.